repos:
- repo: https://github.com/sirosen/fix-smartquotes
  rev: 0.1.1
  hooks:
    - id: fix-smartquotes
- repo: https://github.com/nix-community/nixpkgs-fmt
  rev: master
  hooks:
    - id: nixpkgs-fmt